### ISSUE TITLE
Shaka fails to play HLS with error code 4017 (HLS_INVALID_PLAYLIST_HIERARCHY)

### ISSUE THREAD

**Issue by jaime2m1** [shaka-project/shaka-player#4388]
**Have you read the [Tutorials](http://shaka-player-demo.appspot.com/docs/api/tutorial-welcome.html)?** Yes

**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?** Yes, but [this](https://github.com/shaka-project/shaka-player/issues/3133) hasn't helped me

**What version of Shaka Player are you using?** 4.1.2

I'm trying to play some HLS demo like [https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8](https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8)

I get this error:
Shaka Error MANIFEST.HLS_INVALID_PLAYLIST_HIERARCHY () Error: Shaka Error MANIFEST.HLS_INVALID_PLAYLIST_HIERARCHY ()
    at new shaka.util.Error (shaka-player.compiled.debug.js:79:784)
    at shaka.hls.HlsParser.<anonymous> (shaka-player.compiled.debug.js:566:326)
    at async Promise.all (index 0)
    at async Promise.all (index 0)

**Comment by joeyparrish** [comment]
I don't get the same results for that content.  It plays just fine for me:

https://shaka-player-demo.appspot.com/demo/#asset=https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8

Does that link not work for you?  Are you using a custom app?  What browser are you using?

**Comment by jaime2m1** [comment]
I don't know why it was failing 
I used the example javascript from [here](https://shaka-player-demo.appspot.com/docs/api/tutorial-basic-usage.html) and installed mux, and it worked
