### ISSUE TITLE
Rare test failure

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#4813]
It takes 100-200 test runs on my Linux desktop to reproduce this error, but there is a rare exception in StreamingEngine tests:

```
[INFO] Running test (98 / 100, 1 failed so far)...
Running tests on: Chrome
Chrome 107.0.0.0 (Linux x86_64) StreamingEngine VOD can handle unbuffered seeks FAILED
	Uncaught TypeError: Cannot read properties of null (reading 'getPresentationTime') thrown
	Failed: Unhandled error: TypeError: Cannot read properties of null (reading 'getPresentationTime')
	TypeError: Cannot read properties of null (reading 'getPresentationTime')
	    at shaka.media.StreamingEngine.seeked (lib/media/streaming_engine.js:606:52)
	    at shaka.media.MediaSourcePlayhead.onSeek [as onSeek_] (test/media/streaming_engine_integration.js:223:23)
	    at shaka.media.MediaSourcePlayhead.onSeeking_ (lib/media/playhead.js:379:10)
	    at shaka.media.VideoWrapper.onSeek_ (lib/media/playhead.js:225:20)
	    at HTMLVideoElement.<anonymous> (lib/media/video_wrapper.js:167:66)
	Error: Failed: Unhandled error: TypeError: Cannot read properties of null (reading 'getPresentationTime')
	TypeError: Cannot read properties of null (reading 'getPresentationTime')
	    at shaka.media.StreamingEngine.seeked (lib/media/streaming_engine.js:606:52)
	    at shaka.media.MediaSourcePlayhead.onSeek [as onSeek_] (test/media/streaming_engine_integration.js:223:23)
	    at shaka.media.MediaSourcePlayhead.onSeeking_ (lib/media/playhead.js:379:10)
	    at shaka.media.VideoWrapper.onSeek_ (lib/media/playhead.js:225:20)
	    at HTMLVideoElement.<anonymous> (lib/media/video_wrapper.js:167:66)
	    at <Jasmine>
	    at failOnError (test/test/boot.js:82:3)
	    at test/test/boot.js:102:5
Chrome 107.0.0.0 (Linux x86_64): Executed 2264 of 2274 (1 FAILED) (skipped 10) (6 mins 52.932 secs / 6 mins 50.041 secs)
TOTAL: 1 FAILED, 2263 SUCCESS
```

I was only able to get this backtrace by adding an additional event handles to `test/test/boot.js` to print more info from unhandled global exceptions.

**Comment by joeyparrish** [comment]
375 test runs in a row passed.  I had planned 400, but I'm running out of time to finish cherry-picking and preparing releases, so I'm going to go ahead and merge the fix now.
