### ISSUE TITLE
Shaka Error DRM.INVALID_SERVER_CERTIFICATE trying to store content when serverCertificateUri is set

### ISSUE THREAD

**Issue by Maximusya** [shaka-project/shaka-player#5132]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
YES

**What version of Shaka Player are you using?**
4.3.5

**Can you reproduce the issue with our latest release version?**
YES

**Can you reproduce the issue with the latest code from `main`?**
not tried

**Are you using the demo app or your own custom app?**
both DEMO and custom app

**If custom app, can you reproduce the issue using our demo app?**
YES

**What browser and OS are you using?**
Chrome/Windows

**For embedded devices (smart TVs, etc.), what model and firmware version are you using?**
no

**What are the manifest and license server URIs?**

https://storage.googleapis.com/shaka-demo-assets/dig-the-uke/dash.mpd
https://cwip-shaka-proxy.appspot.com/no_auth

**What configuration are you using?  What is the output of `player.getConfiguration()`?**

**What did you do?**

- Add custom content at https://shaka-player-demo.appspot.com/
  - Manifest URL: https://storage.googleapis.com/shaka-demo-assets/dig-the-uke/dash.mpd
  - Name: Preset certificate
  - License Server URL: https://cwip-shaka-proxy.appspot.com/no_auth
  - License Certificate URL: https://cwip-shaka-proxy.appspot.com/service-cert
- press the download button on the just added content 

**What did you expect to happen?**
I expected the content to be successfully downloaded and be ready to play in offline - without preliminary certificate request at license server URL (https://cwip-shaka-proxy.appspot.com/no_auth).

**What actually happened?**

When I press the download button on the newly added content, I see the app download the certificate, download the manifest - but in the console (and in the page) there is an error and the download process fails:
> Shaka Error DRM.INVALID_SERVER_CERTIFICATE (Failed to execute 'setServerCertificate' on 'MediaKeys': Rejected with system code (52))

> {
    "severity": 2,
    "category": 6,
    "code": 6004,
    "data": [
        "Failed to execute 'setServerCertificate' on 'MediaKeys': Rejected with system code (52)"
    ],
    "handled": false,
    "message": "Shaka Error DRM.INVALID_SERVER_CERTIFICATE (Failed to execute 'setServerCertificate' on 'MediaKeys': Rejected with system code (52))",
    "stack": "Error: Shaka Error DRM.INVALID_SERVER_CERTIFICATE (Failed to execute 'setServerCertificate' on 'MediaKeys': Rejected with system code (52))\n    at new shaka.util.Error (https://shaka-player-demo.appspot.com/lib/util/error.js:94:17)\n    at shaka.media.DrmEngine.setServerCertificate (https://shaka-player-demo.appspot.com/lib/media/drm_engine.js:574:13)\n    at async shaka.offline.Storage.createDrmEngine (https://shaka-player-demo.appspot.com/lib/offline/storage.js:1234:5)\n    at async shaka.offline.Storage.store_ (https://shaka-player-demo.appspot.com/lib/offline/storage.js:357:19)"
}

If instead of downloading I try to PLAY the newly added content, it successfully does so:
- fetches the certificate from https://cwip-shaka-proxy.appspot.com/service-cert
- (does not do server certificate request at https://cwip-shaka-proxy.appspot.com/no_auth!)
- requests a license from https://cwip-shaka-proxy.appspot.com/no_auth

If I remove Certificate URL from the content settings and try to download (or play) the content, it does so - with two requests to https://cwip-shaka-proxy.appspot.com/no_auth (one for certificate, one for license) - as expected.

P.S.: I saw a history of bugs/fixes regarding setServerCertificate, that prove that our expectations are... expected! But failed to find the version of Shaka where it actually works.
- https://github.com/shaka-project/shaka-player/issues/1623
- https://github.com/shaka-project/shaka-player/issues/2644
- ...

**Comment by Maximusya** [comment]
Our debugging session showed that the error was caused by calling `this.mediaKeys_.setServerCertificate` twice inside drmEngine as a part of setting it up in lib/offline/storage.js:createDrmEngine:

```javascript
  async createDrmEngine(manifest, onError, config) {
    goog.asserts.assert(
        this.networkingEngine_,
        'Cannot call |createDrmEngine| after |destroy|');

    /** @type {!shaka.media.DrmEngine} */
    const drmEngine = new shaka.media.DrmEngine({
      netEngine: this.networkingEngine_,
      onError: onError,
      onKeyStatus: () => {},
      onExpirationUpdated: () => {},
      onEvent: () => {},
    });

    drmEngine.configure(config.drm);
    await drmEngine.initForStorage(
        manifest.variants, config.offline.usePersistentLicense);
    await drmEngine.setServerCertificate();
    await drmEngine.createOrLoad();

    return drmEngine;
  }
```

one call is made as a part of `await drmEngine.initForStorage` call stack, and another via `await drmEngine.setServerCertificate();`

Both eventual mediaKeys setServerCertificate calls where added in different time by the commits related to the issues I mentioned.

If we simply comment out explicit `await drmEngine.setServerCertificate();` at https://github.com/shaka-project/shaka-player/blob/main/lib/offline/storage.js#L1231, we no longer get the aforementioned error when downloading content.

We have not run your test suite to find out what breaks if we do this - it just solves this particular error for our setup.

PS: we patched and tried 4.3.5 release sources.
