### ISSUE TITLE
Tizen test failure: stuck on HEVC playback in transmuxer test

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#6273]
This is failing consistently in the lab:

```
Safari 3.0 (Tizen 3.0) Transmuxer Player for muxed content H.265+AAC in TS FAILED
        Error: Timeout waiting for movement from 1.462 to 15
        current time: 10.013
        duration: 10
        ready state: 1
        playback rate: 1
        paused: false
        ended: true
        buffered: {"total":[{"start":0.001,"end":10}],"audio":[{"start":0,"end":9.993}],"video":[{"start":0.001,"end":10}],"text":[]}

        Error: Timeout waiting for movement from 1.462 to 15
        current time: 10.013
        duration: 10
        ready state: 1
	playback rate: 1
	paused: false
	ended: true
	buffered: {"total":[{"start":0.001,"end":10}],"audio":[{"start":0,"end":9.993}],"video":[{"start":0.001,"end":10}],"text":[]}
	    at _class.waitUntilGeneric_ (test/test/util/waiter.js:339:19 <- test/test/util/waiter.js:367:19)
	    at _class.waitUntilPlayheadReaches (test/test/util/waiter.js:133:17 <- test/test/util/waiter.js:152:19)
	    at _class.waitUntilPlayheadReachesOrFailOnTimeout (test/test/util/waiter.js:148:17 <- test/test/util/waiter.js:169:19)
	    at _callee15$ (test/transmuxer/transmuxer_integration.js:372:20 <- test/transmuxer/transmuxer_integration.js:562:29)
	    at tryCatch (node_modules/@babel/polyfill/dist/polyfill.js:6473:40)
	    at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/@babel/polyfill/dist/polyfill.js:6702:22)
	    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/@babel/polyfill/dist/polyfill.js:6525:21)
	    at asyncGeneratorStep (test/ui/ui_integration.js:17:103)
	    at _next (test/transmuxer/transmuxer_integration.js:4:194)
```

**Comment by joeyparrish** [comment]
I've confirmed that 2017 Tizen TVs should have HEVC support, which aligns with the fact that this plays any amount of content at all.  I have yet to debug the test and the transmuxer operation.

**Comment by joeyparrish** [comment]
I should have looked more closely at the output from the failure:

`Error: Timeout waiting for movement from 1.462 to 15`

`current time: 10.013`

`buffered: {"total":[{"start":0.001,"end":10}],"audio":[{"start":0,"end":9.993}],"video":[{"start":0.001,"end":10}],"text":[]}`

We don't have enough content buffered to reach the goal.  The playhead is around 10s, with around 10s buffered, with a goal of 15s.  The timeout is set for 45s after movement begins.

**Comment by joeyparrish** [comment]
And now it's passing without logs.  No clue what's happening.  Not as consistent as I thought.

I could always increase the timeout, but 45s should be long enough to buffer more than one segment.

**Comment by joeyparrish** [comment]
Passed in the nightly tests last night.  Closing as unreproduceable for now.

**Comment by joeyparrish** [comment]
I did 10 manual test runs (full test runs) on Tizen, and this failed in 6/10.  My previous confusion about results with/without logging was due to the inconsistency of the problem.

I'm going to do 10 more runs now with logging enabled.

**Comment by joeyparrish** [comment]
In the cases where it fails, with v2 logging on, we see:

```
DEBUG LOG: ^[[36m'Suggesting Streams...'^[[39m
DEBUG LOG: ^[[36m'Still within switch interval...'^[[39m
DEBUG LOG: ^[[36m'(video:2)', 'checking buffer length'^[[39m 
DEBUG LOG: ^[[36m'(video:2)', 'buffer behind okay:', 'presentationTime=0.001', 'bufferedBehind=0', 'bufferBehind=30', 'evictionGoal=1', 'underflow=30'^[[39m
DEBUG LOG: ^[[36m'(video:2)', 'appended media segment'^[[39m
DEBUG LOG: ^[[36m'(video:2)', 'advancing to next segment', null^[[39m
DEBUG LOG: ^[[36m'(video:2)', 'finished fetch and append', '[{"start":0.001,"end":10}]'^[[39m
DEBUG LOG: ^[[36m'(video:2)', 'updating in 0 seconds'^[[39m
DEBUG LOG: ^[[36m'(video:2)', 'timeNeeded=10'^[[39m
DEBUG LOG: ^[[36m'(video:2)', 'update_:', 'presentationTime=0.03', 'bufferedAhead=9.97'^[[39m
LOG LOG: ^[[36m'(video:2)', 'buffered to end of presentation'^[[39m
DEBUG LOG: ^[[36m'(video:2)', 'calling endOfStream()...'^[[39m
LOG LOG: ^[[36m'movement from 0 to 1 after 1.75 seconds'^[[39m
LOG LOG: ^[[36m'Waiting for movement from 1.263 to 15'^[[39m
ERROR LOG: ^[[36m'Timeout waiting for movement from 1.263 to 15
```

So it seems that it doesn't buffer past 10 because it doesn't believe there is any more content.  Then the text expectation to play until 15 fails, naturally.

In a passing test run, we see:

```
DEBUG LOG: ^[[36m'Suggesting Streams...'^[[39m 
DEBUG LOG: ^[[36m'Still within switch interval...'^[[39m
DEBUG LOG: ^[[36m'(video:2)', 'checking buffer length'^[[39m 
DEBUG LOG: ^[[36m'(video:2)', 'buffer behind okay:', 'presentationTime=0.001', 'bufferedBehind=0', 'bufferBehind=30', 'evictionGoal=1', 'underflow=30'^[[39m
DEBUG LOG: ^[[36m'(video:2)', 'appended media segment'^[[39m
DEBUG LOG: ^[[36m'(video:2)', 'advancing to next segment', null^[[39m
DEBUG LOG: ^[[36m'(video:2)', 'finished fetch and append', '[{"start":0.001,"end":10}]'^[[39m
INFO LOG: ^[[36m'Jumping forward', 0.001, 'seconds because of gap before start time of', 0.001^[[39m
DEBUG LOG: ^[[36m'(video:2)', 'updating in 0 seconds'^[[39m
DEBUG LOG: ^[[36m'Playhead in safe region or in buffered region.'^[[39m
DEBUG LOG: ^[[36m'Seek to 0.001'^[[39m
LOG LOG: ^[[36m'(all): seeked: buffered seek: presentationTime=0.001'^[[39m
DEBUG LOG: ^[[36m'(video:2)', 'timeNeeded=10'^[[39m
DEBUG LOG: ^[[36m'(video:2)', 'update_:', 'presentationTime=0.001', 'bufferedAhead=9.999'^[[39m
LOG LOG: ^[[36m'(video:2)', 'buffered to end of presentation'^[[39m 
DEBUG LOG: ^[[36m'(video:2)', 'calling endOfStream()...'^[[39m
LOG LOG: ^[[36m'movement from 0 to 1 after 2.20 seconds'^[[39m
LOG LOG: ^[[36m'Waiting for movement from 1.444 to 15'^[[39m
LOG LOG: ^[[36m'movement from 1.444 to 15 after 8.53 seconds'^[[39m
```

Oddly, it still stops buffering after 10s of content, but somehow plays to 15 anyway...

In fact, there are only two segments in the content, each marked as 5s long:

```
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:5
#EXT-X-MEDIA-SEQUENCE:0
#EXTINF:5.000000,
0.ts
#EXTINF:5.000000,
1.ts
#EXT-X-ENDLIST
```

FFMpeg says each segment is indeed 5.05 seconds long.  So how is this test working ever, on any platform?

**Comment by joeyparrish** [comment]
These test assets are shorter than the amount of time the test is meant to play:
 - test/test/assets/hls-ts-muxed-aac-h265/media.m3u8 (2 segments x 5s vs 15s playback)
 - test/test/assets/hls-ts-h265/index.m3u8 (1 segment x 12s vs 15s playback)

How are they passing?

**Comment by joeyparrish** [comment]
We're using `waiter.waitUntilPlayheadReachesOrFailOnTimeout`, which uses this logic:

```js
if (mediaElement.currentTime >= timeGoal || mediaElement.ended) {
```

So the `.ended` attribute is saving us, except where it flakes on Tizen.

I feel confident updating the tests and/or assets now to fix this.
