### ISSUE TITLE
Tests failing with LOAD_INTERRUPTED

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-player#6274]
These are failing consistently in the lab:

```
Chrome 90.0.4430.225 (Chromecast 1.56.500000) Player Load Graph without media source loading ignores media source path FAILED
        Unhandled promise rejection: shaka.util.Error {
          "severity": 2,
          "category": 7,
          "code": 7000,
          "data": [],
          "handled": false,
          "message": "Shaka Error PLAYER.LOAD_INTERRUPTED ()"
        } thrown
        Failed: Unhandled rejection in Promise: shaka.util.Error {
          "severity": 2,
          "category": 7,
          "code": 7000,
          "data": [],
	  "handled": false,
	  "message": "Shaka Error PLAYER.LOAD_INTERRUPTED ()"
	}
	Error: Failed: Unhandled rejection in Promise: shaka.util.Error {
	  "severity": 2,
	  "category": 7,
	  "code": 7000,
	  "data": [],
	  "handled": false,
	  "message": "Shaka Error PLAYER.LOAD_INTERRUPTED ()"
	}
	    at <Jasmine>
	    at failOnError (test/test/boot.js:82:3 <- test/test/boot.js:102:3)
	    at test/test/boot.js:94:5 <- test/test/boot.js:115:5
```

```
Safari 3.0 (Tizen 3.0) Player unloading unloads properly after DRM error FAILED
        Shaka Error 7000
        error properties: shaka.util.Error {
          "severity": 2,
          "category": 7,
          "code": 7000,
          "data": [],
          "handled": false
        }
        Error: Shaka Error 7000
            at Error (native)
            at new P (dist/shaka-player.ui.js:77:311)
            at ya.eval [as h] (dist/shaka-player.ui.js:537:450)
            at Ba (dist/shaka-player.ui.js:21:299)
	    at Ca.next (dist/shaka-player.ui.js:22:91)
	    at b (dist/shaka-player.ui.js:22:330)
	    at run (node_modules/@babel/polyfill/dist/polyfill.js:4536:22)
	    at node_modules/@babel/polyfill/dist/polyfill.js:4553:30
	    at MutationObserver.flush (node_modules/@babel/polyfill/dist/polyfill.js:1665:9)
```

**Comment by joeyparrish** [comment]
These are both caused by tests that either don't await their results or that await Promises that are _meant_ to be interrupted.  The fact that the second test doesn't always fail on all platforms the way it is written means it is only testing the right thing on systems that are slow like our 2017 Tizen.
