### ISSUE TITLE
Transmuxing Error for some HLS streams

### ISSUE THREAD

**Issue by efkann** [shaka-project/shaka-player#7812]
**Have you read the [FAQ](https://bit.ly/ShakaFAQ) and checked for duplicate open issues?**
Yes

**What version of Shaka Player are you using?**

4.12.5, 4.9.2-caf3, 4.9.2-caf2

**Can you reproduce the issue with our latest release version?**
Yes

**Can you reproduce the issue with the latest code from `main`?**
Yes

**Are you using the demo app or your own custom app?**
Demo app 

**If custom app, can you reproduce the issue using our demo app?**
Yes

**What browser and OS are you using?**
Latest Chrome version, macOS

**What are the manifest and license server URIs?**

These streams are from Exoplayer's Cast demo app.

HLS (adaptive): Apple 4x3 basic stream (TS/h264/aac)
https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8

HLS (1280x720): Designing For Google Cast (TS/h264/aac)

https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/hls/DesigningForGoogleCast.m3u8

I don't use any extra configuration.

**What did you do?**

Tested casting the streams from the Exoplayer Cast Demo app and they gave an error like below.

```js
{"type":"ERROR","detailedErrorCode":100,"severity":2,"error":{"shakaErrorCode":3018,"shakaErrorData":["https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/gear4/fileSequence1.ts"],"shakaErrorStack":"Error: Shaka Error 3018\n    at new T (https://ajax.googleapis.com/ajax/libs/shaka-player/4.12.5/shaka-player.compiled.js:66:296)\n    at HD.r.transmux (https://ajax.googleapis.com/ajax/libs/shaka-player/4.12.5/shaka-player.compiled.js:1498:205)\n    at Ea.h (https://ajax.googleapis.com/ajax/libs/shaka-player/4.12.5/shaka-player.compiled.js:412:359)\n    at Ha (https://ajax.googleapis.com/ajax/libs/shaka-player/4.12.5/shaka-player.compiled.js:21:299)\n    at Ja.next (https://ajax.googleapis.com/ajax/libs/shaka-player/4.12.5/shaka-player.compiled.js:22:91)\n    at https://ajax.googleapis.com/ajax/libs/shaka-player/4.12.5/shaka-player.compiled.js:22:484\n    at new Promise (<anonymous>)\n    at Ka (https://ajax.googleapis.com/ajax/libs/shaka-player/4.12.5/shaka-player.compiled.js:22:377)\n    at P (https://ajax.googleapis.com/ajax/libs/shaka-player/4.12.5/shaka-player.compiled.js:23:22)\n    at vk (https://ajax.googleapis.com/ajax/libs/shaka-player/4.12.5/shaka-player.compiled.js:410:149)","shakaErrorSeverity":2}} 
```

Also tested at https://shaka-player-demo.appspot.com but still produces errors like:
```
[Shaka Error MEDIA.TRANSMUXING_FAILED (https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/hls/designing_for_google_cast/fileSequence0.ts)](https://shaka-player-demo.appspot.com/docs/api/shaka.util.Error.html#value:3018)
```

**What did you expect to happen?**

These streams were working on Web Receiver if you dont opt-in with `useShakaForHls: true` and add a line like

`loadRequestData.media.hlsSegmentFormat = cast.framework.messages.HlsSegmentFormat.TS;`

However, after opting-in to use Shaka for HLS streams, they showed errors.

For versions of `4.12.5`, `4.9.2-caf3`, `4.9.2-caf2` they produce the transmuxing error.

Interestingly downgrading my Web Receiver's Shaka version to `4.3.4` makes the first `HLS (adaptive): Apple 4x3 basic stream` stream work. But, produces different error for the second stream like below:

```
[cast.framework.media.ShakaPlayer] category: 4
code: 4032
stack: undefined
severity: CRITICAL
data: []
```

**Are you planning to send a PR to fix it?**
It's probably beyond my level of understanding

**Comment by avelad** [comment]
https://commondatastorage.googleapis.com/gtv-videos-bucket/CastVideos/hls/DesigningForGoogleCast.m3u8 --> PR to fix it: https://github.com/shaka-project/shaka-player/pull/7813

https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_4x3/bipbop_4x3_variant.m3u8 --> I don't have a complete solution yet, but part of the solution is included in the other PR.
